### ISSUE TITLE
`-Wgnu-zero-variadic-macro-arguments` generated by use of the `-pedantic` flag

### ISSUE THREAD

**Issue by LeonineKing1199** [pdimov/describe#12]
Using clang 11 with `-pedantic`, Describe generates warnings around: `-Wgnu-zero-variadic-macro-arguments` in the `BOOST_DESCRIBE_STRUCT` macro when no bases are specified.

**Comment by pdimov** [comment]
I suppose you could try `(,)` instead of `()` (or use `-std=c++20` where zero arguments are explicitly allowed by the standard IIRC) but in general I find `-pedantic` under Clang mostly unusable as it's too pedantic.

**Comment by LeonineKing1199** [comment]
I tried `(,)` and I still got the warning. Upgrading to C++20 is definitely on the roadmap for sure but I found it easier to simply just remove `-pedantic` from the build.

I'll close this as something that doesn't need to be fixed.
